spring:
  
  
  application:
    name: Employe
  datasource:
    url: jdbc:mysql://localhost/employe?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    
    open-in-view: true
    database: MYSQL
    show-sql: true
    
    hibernate: 
      
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8000